### ISSUE TITLE
開発環境のセットアップ

### ISSUE THREAD

**Issue by sagaekeiga** [Hayato07/To-Do#1]
`rails new`で環境を構築し、gitへあげる。
Cloud9だとrails newしなくて大丈夫なやつですよね？
とりあえずこのレポジトリにアプリをpushしてしまいましょう！

**Comment by Hayato07** [comment]
大丈夫なんですか！？
一応、rails newでToDoという名前を付けてgitへあげてみました。

**Comment by sagaekeiga** [comment]
大丈夫です！

**Comment by sagaekeiga** [comment]
[![LGTM](https://www.lgtm.in/p/SrKaqnqXp)](https://www.lgtm.in/i/SrKaqnqXp)
